CONTIKI_PROJECT = example-shell
all: $(CONTIKI_PROJECT)

APPS = serial-shell
APPS += about 
#APPS += dhcp

CONTIKI = ../..
#CONTIKI_WITH_RIME = 1
CONTIKI_WITH_IPV6 = 1
include $(CONTIKI)/Makefile.include
